name: Run Azure Login with OIDC
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Azure Login'
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

      - name: 'Run az commands'
        run: |
          az account show
          az group list
