name: 🚀 Deploy to SWA


permissions:
  issues: write
  contents: read
  pull-requests: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Azure Static Web Apps 🚀
        uses: svrooij/azure-static-web-app-deploy-action@main # Replace 'main' with a specific tag for security reasons
        with:
          tenant_id: ${{ secrets.AZURE_TENANTID }} # be sure to set this secret in your repository settings
          client_id: ${{ secrets.AZURE_CLIENTID }} # be sure to set this secret in your repository settings
          static_web_app_name: 'Testing'
          app_location: '.'
          api_location: ''
          swa_environment: 'production'
